[package]
name = "the-book"
version = "0.1.0"
authors = ["Fabio Gavilondo <fgavilondo@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# external packages we depend on specified below
[dependencies]
futures = "0.3.5"
